### ISSUE TITLE
To Do list 

### ISSUE THREAD

**Issue by rjsmethurst** [dotastro/hacks-collector#1]
- [x] Improve README
- [x] Develop webform
- [x] Agree on keywords
- [x] Aggregate previous hacks
- [ ] Add yaml metadata for each meeting
- [x] Turn each submitted hack into github page showcasing hack
- [x] Add information about where to create file
- [x] Add information on how to add a file through GitHub
- [x] Add a template file
- [x] Add info on what to call each file
- [ ] Make template that tells people how to check submission and how to fix submission

**Comment by aallan** [comment]
Might want to annotate the top level directory listing "dotastro 1" "dotastro 2" with locations. I know I remember the meetings more by where I was than by which one it was.

**Comment by astrofrog** [comment]
I'm going to close this and open a separate issue to keep track of the 'template' idea.
