### ISSUE TITLE
Change the name

### ISSUE THREAD

**Issue by zemogle** [dotastro/hacks-collector#55]
Is it too late to change to "Hacks Collector"?

**Comment by astrofrog** [comment]
I don't *think* anything will break if we change the name because GitHub should forward any URLs

So I can change the name of the repo to ``hacks-collector``

Any objections @eteq @dbouquin @drarnakarick @rjsmethurst?

**Comment by eteq** [comment]
It will break the automated build machinery which has the name hard-coded in.  But presumably if you just change the name in https://github.com/dotastro/hack-list-submission-app at the same time as this it should work.  It'll also have to be updated on heroku (which I think I have to do), but that's just a simple push at the right time.

**Comment by zemogle** [comment]
Cool. When do we want to coordinate this? Maybe easier if @eteq is granted permission to change the name and does both  steps?

**Comment by eteq** [comment]
That could work, although it should be a simple find-and replace.  You (@zemogle) or @astrofrog can just do it when convenient and then I can push it up to heroku if you ping me when you do it.

**Comment by eteq** [comment]
Done!

**Comment by zemogle** [comment]
Awesomeness
